Allow bytes as well
adafruit/Adafruit_CircuitPython_FRAM pull request #25
Opened 2021-03-11 01:32 UTC by caternuson

For #24. Using `bytes` was essentially already supported. Just needed to let the driver know how cool it was.

```python
Adafruit CircuitPython 6.1.0 on 2021-01-21; Adafruit QT Py M0 with samd21e18
>>> import board
>>> import adafruit_fram
>>> fram = adafruit_fram.FRAM_I2C(board.I2C())
>>> message = b'Python is fun!'
>>> fram[0] = message
>>> fram[0:len(message)-1]
bytearray(b'Python is fun!')
>>> 
```

2021-03-11 19:00 UTC, tannewt requested changes
This is a bit weird for python because `fram[0] = [0,1,2,3]` would store the list at index 0, not treat it as a starting index. Instead you would use slices `fram[0:3] = [0,1,2,3]`. I believe this is how nvm works already. Mind look into switching this?

2021-03-11 19:12 UTC, caternuson commented
I was sort of wondering about that too. Do you think that'd be better as a separate issue?

I guess the idea was to make it easier? There's no way to actually store all of `[0,1,2,3]` at `fram[0]`. And that syntax doesn't require one to figure out the math for the slice values on the left hand side `fram[0:3]`. But I'm just guessing.

2021-03-13 00:41 UTC, tannewt approved these changes
Fine with me if you want to do it later. I do think it'd be good to make consistent at some point.

2021-03-14 22:30 UTC, caternuson commented
Yep, agree. Just not sure how much of a thread it will pull to change here. And can use `nvm` as a reference. I'll open the new issue.

2021-03-14 22:35 UTC, ladyada approved these changes

2021-03-14 22:46 UTC, merged