Update ValueError text, example files
adafruit/Adafruit_CircuitPython_FRAM pull request #32
Opened 2021-12-18 23:26 UTC by tekktrik

Addresses Issue #29 by changing the ValueError raised to be clearer, and to update the example files to get and set multiple memory addresses with slices correctly.

2021-12-20 20:29 UTC, FoamyGuy requested changes
Thanks @tekktrik The error text looks good to me now.

have one other small request.

2021-12-20 20:29 UTC, FoamyGuy commented on examples/fram_i2c_simpletest.py
> +fram[0:100] = values
Lets keep the writes commented out in the example that way it's harder for someone to unknowingly cause wear on their device by running the example unmodified.

2021-12-20 20:29 UTC, FoamyGuy commented on examples/fram_spi_simpletest.py
> +fram[0:100] = values
Same with these ones lets keep them commented out.

2021-12-21 14:31 UTC, tekktrik commented
Thanks for the feedback!  Resubmitted changes for review.

2021-12-21 14:34 UTC, FoamyGuy approved these changes
Looks good to me

2021-12-21 14:34 UTC, merged